name: staging_deployment

on:
  push:
    tags:
      - v**-staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          npm install
      - name: Building application
        run: |
          npm run build --
      - name: Setting up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Uploading to STAGING EC2
        run: |
          mkdir ~/.ssh
          echo -e "${{ secrets.STAGING_PRIVATE_KEY }}" > ~/.ssh/xgames-keypair
          chmod 400 ~/.ssh/xgames-keypair
          rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/xgames-keypair" -r dist/* ${{ secrets.STAGING_USERNAME }}@${{ secrets.STAGING_HOST }}:${{ secrets.STAGING_PATH }}
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/xgames-keypair ${{ secrets.STAGING_USERNAME }}@${{ secrets.STAGING_HOST }} 'sudo systemctl restart nginx'
